FROM node:20.17.0-alpine

RUN apk add --no-cache bash curl
RUN curl -sfS https://dotenvx.sh/install.sh | sh

WORKDIR /usr/src/app
COPY package.json .
COPY package-lock.json .
RUN npm ci --ignore-scripts

COPY . /usr/src/app
RUN npx prisma generate
RUN npm run build

CMD ["dotenvx", "run", "--strict", "--", "npm", "run", "start:prod"]
